# Generated by Django 4.2.4 on 2023-09-12 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0003_contactform_rename_contactus_apprenticeship'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApprenticeShip',
        ),
        migrations.DeleteModel(
            name='ContactForm',
        ),
    ]
