# Generated by Django 4.2.4 on 2023-09-19 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0006_apprenticeship_feedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='review',
            new_name='Feedback',
        ),
    ]
